name: SYB

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    name: Tests

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            ocaml-compiler: 5.5.0
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: Build
        run: |
          opam install -t --yes .

